In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/marketing-strategy-personalised-offer/sample.csv
/kaggle/input/marketing-strategy-personalised-offer/train_data.csv
/kaggle/input/marketing-strategy-personalised-offer/test_data.csv

In [2]:
# Reading the data 
train_data=pd.read_csv('/kaggle/input/marketing-strategy-personalised-offer/train_data.csv')
train_data.shape

(12379, 31)

In [3]:
train_data.head()

,offer expiration,income_range,no_visited_Cold drinks,travelled_more_than_15mins_for_offer,Restaur_spend_less_than20,Marital Status,restaurant type,age,Prefer western over chinese,travelled_more_than_25mins_for_offer,...,restuarant_opposite_direction_house,has Children,visit restaurant with rating (avg),temperature,Restaur_spend_greater_than20,Travel Time,Climate,drop location,Prefer home food,Offer Accepted
0,2days,₹100000 or More,4~8,1,less1,Married partner,4 star restaurant,36,0,0,...,0,0,4,67,less1,22,Spring,Location B,0,No
1,2days,₹87500 - ₹99999,4~8,0,4~8,Married partner,Take-away restaurant,50plus,0,0,...,0,1,3,89,1~3,18,Summer,Location B,0,Yes
2,2days,₹87500 - ₹99999,less1,1,1~3,Single,Cold drinks,26,1,0,...,1,1,4,67,less1,7,Winter,Location A,1,Yes
3,10hours,₹37500 - ₹49999,less1,0,1~3,Single,Take-away restaurant,46,1,0,...,0,1,3,89,1~3,7,Summer,Location C,0,No
4,2days,₹100000 or More,never,1,1~3,Single,4 star restaurant,21,0,1,...,1,0,3,40,less1,7,Summer,Location C,0,No

In [4]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12379 entries, 0 to 12378
Data columns (total 31 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   offer expiration                      12379 non-null  object
 1   income_range                          12379 non-null  object
 2   no_visited_Cold drinks                12181 non-null  object
 3   travelled_more_than_15mins_for_offer  12379 non-null  int64
 4   Restaur_spend_less_than20             12258 non-null  object
 5   Marital Status                        12379 non-null  object
 6   restaurant type                       12379 non-null  object
 7   age                                   12379 non-null  object
 8   Prefer western over chinese           12379 non-null  int64
 9   travelled_more_than_25mins_for_offer  12379 non-null  int64
 10  travelled_more_than_5mins_for_offer   12379 non-null  int64
 11  no_visited_bars                       12286 non-null  object
 12  gender                                12379 non-null  object
 13  car                                   111 non-null    object
 14  restuarant_same_direction_house       12379 non-null  int64
 15  Cooks regularly                       12379 non-null  int64
 16  Customer type                         12379 non-null  object
 17  Qualification                         12379 non-null  object
 18  is foodie                             12379 non-null  int64
 19  no_Take-aways                         12235 non-null  object
 20  Job/Job Industry                      12379 non-null  object
 21  restuarant_opposite_direction_house   12379 non-null  int64
 22  has Children                          12379 non-null  int64
 23  visit restaurant with rating (avg)    12379 non-null  int64
 24  temperature                           12379 non-null  int64
 25  Restaur_spend_greater_than20          12219 non-null  object
 26  Travel Time                           12379 non-null  int64
 27  Climate                               12379 non-null  object
 28  drop location                         12379 non-null  object
 29  Prefer home food                      12379 non-null  int64
 30  Offer Accepted                        12379 non-null  object
dtypes: int64(13), object(18)
memory usage: 2.9+ MB

In [5]:
column_names = train_data.columns
print(column_names)

Index(['offer expiration', 'income_range', 'no_visited_Cold drinks',
       'travelled_more_than_15mins_for_offer', 'Restaur_spend_less_than20',
       'Marital Status', 'restaurant type', 'age',
       'Prefer western over chinese', 'travelled_more_than_25mins_for_offer',
       'travelled_more_than_5mins_for_offer', 'no_visited_bars', 'gender',
       'car', 'restuarant_same_direction_house', 'Cooks regularly',
       'Customer type', 'Qualification', 'is foodie', 'no_Take-aways',
       'Job/Job Industry', 'restuarant_opposite_direction_house',
       'has Children', 'visit restaurant with rating (avg)', 'temperature',
       'Restaur_spend_greater_than20', 'Travel Time', 'Climate',
       'drop location', 'Prefer home food', 'Offer Accepted'],
      dtype='object')

In [6]:
train_data.corr()

,travelled_more_than_15mins_for_offer,Prefer western over chinese,travelled_more_than_25mins_for_offer,travelled_more_than_5mins_for_offer,restuarant_same_direction_house,Cooks regularly,is foodie,restuarant_opposite_direction_house,has Children,visit restaurant with rating (avg),temperature,Travel Time,Prefer home food
travelled_more_than_15mins_for_offer,1.000000,-0.006240,0.260010,NaN,-0.235369,-0.007298,-0.005033,0.244595,0.061522,0.004972,-0.087966,-0.039006,0.001566
Prefer western over chinese,-0.006240,1.000000,-0.006902,NaN,-0.000240,0.000577,-0.005162,0.001003,-0.002226,0.008355,-0.003658,-0.005157,0.004667
travelled_more_than_25mins_for_offer,0.260010,-0.006902,1.000000,NaN,-0.157145,0.001324,-0.000996,0.156636,-0.018346,-0.000696,-0.116672,-0.109257,0.006725
travelled_more_than_5mins_for_offer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
restuarant_same_direction_house,-0.235369,-0.000240,-0.157145,NaN,1.000000,-0.012155,0.013742,-0.808701,-0.021634,0.003221,0.053245,0.009562,-0.003522
Cooks regularly,-0.007298,0.000577,0.001324,NaN,-0.012155,1.000000,0.007518,0.006251,-0.010889,0.002777,0.007401,-0.008858,0.008824
is foodie,-0.005033,-0.005162,-0.000996,NaN,0.013742,0.007518,1.000000,-0.011403,-0.008662,0.011809,0.006355,-0.014068,0.017265
restuarant_opposite_direction_house,0.244595,0.001003,0.156636,NaN,-0.808701,0.006251,-0.011403,1.000000,0.022803,-0.005848,-0.045545,-0.004580,-0.000461
has Children,0.061522,-0.002226,-0.018346,NaN,-0.021634,-0.010889,-0.008662,0.022803,1.000000,0.000433,-0.014912,0.014161,0.001640
visit restaurant with rating (avg),0.004972,0.008355,-0.000696,NaN,0.003221,0.002777,0.011809,-0.005848,0.000433,1.000000,-0.001313,0.004615,-0.003867
temperature,-0.087966,-0.003658,-0.116672,NaN,0.053245,0.007401,0.006355,-0.045545,-0.014912,-0.001313,1.000000,-0.021197,0.000905
Travel Time,-0.039006,-0.005157,-0.109257,NaN,0.009562,-0.008858,-0.014068,-0.004580,0.014161,0.004615,-0.021197,1.000000,0.004937
Prefer home food,0.001566,0.004667,0.006725,NaN,-0.003522,0.008824,0.017265,-0.000461,0.001640,-0.003867,0.000905,0.004937,1.000000

In [7]:
num_col=[]
cat_col=[]
for i in train_data.columns:
    if train_data[i].dtype=='int64':
        num_col = num_col+[i]
    else:
        cat_col = cat_col+[i]
print("numerical columns are:",num_col,'\n')
print("number of numerical columns are:",len(num_col),'\n')
print("categorical columns are:",cat_col,'\n')
print('number of categorial columns are:',len(cat_col),'\n')

numerical columns are: ['travelled_more_than_15mins_for_offer', 'Prefer western over chinese', 'travelled_more_than_25mins_for_offer', 'travelled_more_than_5mins_for_offer', 'restuarant_same_direction_house', 'Cooks regularly', 'is foodie', 'restuarant_opposite_direction_house', 'has Children', 'visit restaurant with rating (avg)', 'temperature', 'Travel Time', 'Prefer home food']

number of numerical columns are: 13

categorical columns are: ['offer expiration', 'income_range', 'no_visited_Cold drinks', 'Restaur_spend_less_than20', 'Marital Status', 'restaurant type', 'age', 'no_visited_bars', 'gender', 'car', 'Customer type', 'Qualification', 'no_Take-aways', 'Job/Job Industry', 'Restaur_spend_greater_than20', 'Climate', 'drop location', 'Offer Accepted']

number of categorial columns are: 18

In [8]:
for i in num_col:
    print("number of unique values in {} are {}".format(i,len(train_data[i].unique())))
    print("Unique values of {} are {}".format(i,train_data[i].unique()))

number of unique values in travelled_more_than_15mins_for_offer are 2
Unique values of travelled_more_than_15mins_for_offer are [1 0]
number of unique values in Prefer western over chinese are 2
Unique values of Prefer western over chinese are [0 1]
number of unique values in travelled_more_than_25mins_for_offer are 2
Unique values of travelled_more_than_25mins_for_offer are [0 1]
number of unique values in travelled_more_than_5mins_for_offer are 1
Unique values of travelled_more_than_5mins_for_offer are [1]
number of unique values in restuarant_same_direction_house are 2
Unique values of restuarant_same_direction_house are [0 1]
number of unique values in Cooks regularly are 2
Unique values of Cooks regularly are [1 0]
number of unique values in is foodie are 2
Unique values of is foodie are [0 1]
number of unique values in restuarant_opposite_direction_house are 2
Unique values of restuarant_opposite_direction_house are [0 1]
number of unique values in has Children are 2
Unique values of has Children are [0 1]
number of unique values in visit restaurant with rating (avg) are 5
Unique values of visit restaurant with rating (avg) are [4 3 0 1 2]
number of unique values in temperature are 3
Unique values of temperature are [67 89 40]
number of unique values in Travel Time are 5
Unique values of Travel Time are [22 18  7 10 14]
number of unique values in Prefer home food are 2
Unique values of Prefer home food are [0 1]

In [9]:
for i in cat_col:
    print("number of unique values in {} are {}".format(i,len(train_data[i].unique())))
    print("Unique values of {} are {}".format(i,train_data[i].unique()))

number of unique values in offer expiration are 2
Unique values of offer expiration are ['2days' '10hours']
number of unique values in income_range are 9
Unique values of income_range are ['₹100000 or More' '₹87500 - ₹99999' '₹37500 - ₹49999' 'Less than ₹12500'
 '₹50000 - ₹62499' '₹12500 - ₹24999' '₹75000 - ₹87499' '₹25000 - ₹37499'
 '₹62500 - ₹74999']
number of unique values in no_visited_Cold drinks are 6
Unique values of no_visited_Cold drinks are ['4~8' 'less1' 'never' '1~3' 'gt8' nan]
number of unique values in Restaur_spend_less_than20 are 6
Unique values of Restaur_spend_less_than20 are ['less1' '4~8' '1~3' 'gt8' 'never' nan]
number of unique values in Marital Status are 5
Unique values of Marital Status are ['Married partner' 'Single' 'Divorced' 'Unmarried partner' 'Widowed']
number of unique values in restaurant type are 5
Unique values of restaurant type are ['4 star restaurant' 'Take-away restaurant' 'Cold drinks'
 'Restaurant with pub' '2 star restaurant']
number of unique values in age are 8
Unique values of age are ['36' '50plus' '26' '46' '21' 'below21' '41' '31']
number of unique values in no_visited_bars are 6
Unique values of no_visited_bars are ['less1' 'never' '1~3' nan '4~8' 'gt8']
number of unique values in gender are 2
Unique values of gender are ['Female' 'Male']
number of unique values in car are 6
Unique values of car are [nan 'Mazda5' 'Car that is too old to install Onstar :D' 'crossover'
 'Scooter and motorcycle' 'do not drive']
number of unique values in Customer type are 4
Unique values of Customer type are ['Individual' 'With Family' 'With Kids' 'With Colleagues']
number of unique values in Qualification are 6
Unique values of Qualification are ['Bachelors degree' 'Some college - no degree'
 'Graduate degree (Masters or Doctorate)' 'Associates degree'
 'High School Graduate' 'Some High School']
number of unique values in no_Take-aways are 6
Unique values of no_Take-aways are ['1~3' 'gt8' '4~8' 'less1' nan 'never']
number of unique values in Job/Job Industry are 25
Unique values of Job/Job Industry are ['Unemployed' 'Arts Design Entertainment Sports & Media' 'Sales & Related'
 'Student' 'Business & Financial' 'Computer & Mathematical'
 'Office & Administrative Support' 'Management' 'Healthcare Support'
 'Life Physical Social Science' 'Installation Maintenance & Repair'
 'Legal' 'Community & Social Services' 'Education&Training&Library'
 'Construction & Extraction' 'Healthcare Practitioners & Technical'
 'Transportation & Material Moving' 'Retired' 'Architecture & Engineering'
 'Production Occupations' 'Farming Fishing & Forestry'
 'Protective Service' 'Personal Care & Service'
 'Food Preparation & Serving Related'
 'Building & Grounds Cleaning & Maintenance']
number of unique values in Restaur_spend_greater_than20 are 6
Unique values of Restaur_spend_greater_than20 are ['less1' '1~3' 'never' 'gt8' nan '4~8']
number of unique values in Climate are 3
Unique values of Climate are ['Spring' 'Summer' 'Winter']
number of unique values in drop location are 3
Unique values of drop location are ['Location B' 'Location A' 'Location C']
number of unique values in Offer Accepted are 2
Unique values of Offer Accepted are ['No' 'Yes']

In [10]:
# Number of unique values in Job/Job Industry are 25 and this feature is a nominal categorical feature

In [11]:
# check for missing values
train_data.isnull().sum()

offer expiration                            0
income_range                                0
no_visited_Cold drinks                    198
travelled_more_than_15mins_for_offer        0
Restaur_spend_less_than20                 121
Marital Status                              0
restaurant type                             0
age                                         0
Prefer western over chinese                 0
travelled_more_than_25mins_for_offer        0
travelled_more_than_5mins_for_offer         0
no_visited_bars                            93
gender                                      0
car                                     12268
restuarant_same_direction_house             0
Cooks regularly                             0
Customer type                               0
Qualification                               0
is foodie                                   0
no_Take-aways                             144
Job/Job Industry                            0
restuarant_opposite_direction_house         0
has Children                                0
visit restaurant with rating (avg)          0
temperature                                 0
Restaur_spend_greater_than20              160
Travel Time                                 0
Climate                                     0
drop location                               0
Prefer home food                            0
Offer Accepted                              0
dtype: int64

In [12]:
# car feature having more number of missing values

In [13]:
missing_columns =['no_visited_Cold drinks','Restaur_spend_less_than20','no_visited_bars','car','no_Take-aways','Restaur_spend_greater_than20']
for i in missing_columns:
    print(train_data[i].value_counts())

less1    3304
1~3      3147
never    2903
4~8      1776
gt8      1051
Name: no_visited_Cold drinks, dtype: int64
1~3      5248
4~8      3485
less1    2052
gt8      1265
never     208
Name: Restaur_spend_less_than20, dtype: int64
never    5064
less1    3397
1~3      2430
4~8      1047
gt8       348
Name: no_visited_bars, dtype: int64
Car that is too old to install Onstar :D    24
Scooter and motorcycle                      23
do not drive                                22
Mazda5                                      21
crossover                                   21
Name: car, dtype: int64
1~3      4650
4~8      4115
less1    1762
gt8      1568
never     140
Name: no_Take-aways, dtype: int64
less1    5992
1~3      3216
never    2033
4~8       711
gt8       267
Name: Restaur_spend_greater_than20, dtype: int64

In [14]:
# convert ordinal categorical data into numerical data
train_data['no_visited_Cold drinks'].replace({'never':-1,'less1':0,'1~3':2,'4~8':6,'gt8':9},inplace=True)
train_data['Restaur_spend_less_than20'].replace({'never':-1,'less1':0,'1~3':2,'4~8':6,'gt8':9},inplace=True)
train_data['no_visited_bars'].replace({'never':-1,'less1':0,'1~3':2,'4~8':6,'gt8':9},inplace=True)
train_data['no_Take-aways'].replace({'never':-1,'less1':0,'1~3':2,'4~8':6,'gt8':9},inplace=True)
train_data['Restaur_spend_greater_than20'].replace({'never':-1,'less1':0,'1~3':2,'4~8':6,'gt8':9},inplace=True)

In [15]:
# Dropping 'Job/job industry' column because more number of unique values and 'car' column because more missing values
train_data.drop(columns=['Job/Job Industry','car'],inplace=True)
print(train_data.columns)
print(train_data.shape)

Index(['offer expiration', 'income_range', 'no_visited_Cold drinks',
       'travelled_more_than_15mins_for_offer', 'Restaur_spend_less_than20',
       'Marital Status', 'restaurant type', 'age',
       'Prefer western over chinese', 'travelled_more_than_25mins_for_offer',
       'travelled_more_than_5mins_for_offer', 'no_visited_bars', 'gender',
       'restuarant_same_direction_house', 'Cooks regularly', 'Customer type',
       'Qualification', 'is foodie', 'no_Take-aways',
       'restuarant_opposite_direction_house', 'has Children',
       'visit restaurant with rating (avg)', 'temperature',
       'Restaur_spend_greater_than20', 'Travel Time', 'Climate',
       'drop location', 'Prefer home food', 'Offer Accepted'],
      dtype='object')
(12379, 29)

In [16]:
train_data['offer expiration'].replace({'2days':48,'10hours':10},inplace=True)

In [17]:
# ordinal data
train_data['income_range'].replace({'Less than ₹12500':0,'₹12500 - ₹24999':1,'₹25000 - ₹37499':2,
                                       '₹37500 - ₹49999':3,'₹50000 - ₹62499':4,'₹62500 - ₹74999':5,
                                       '₹75000 - ₹87499':6,'₹87500 - ₹99999':7,'₹100000 or More':8},inplace=True)
train_data['age'].replace({'below21':20,'21':21,'26':26,'31':31,'36':36,'41':41,'46':46,
                          '50plus':51},inplace=True)
train_data['Qualification'].replace({'Some High School':0,'High School Graduate':1,'Some college - no degree':2,
                'Bachelors degree':3,'Associates degree':4,'Graduate degree (Masters or Doctorate)':5},inplace=True)

In [18]:
# Handling nominal data
import numpy as np
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()

In [19]:
ohe.fit_transform(train_data[['Marital Status','restaurant type','gender','Customer type','Climate','drop location']]).toarray()

array([[0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.]])

In [20]:

feature_array =ohe.fit_transform(train_data[['Marital Status','restaurant type','gender','Customer type','Climate','drop location']]).toarray()
feature_labels =ohe.categories_
feature_labels

[array(['Divorced', 'Married partner', 'Single', 'Unmarried partner',
        'Widowed'], dtype=object),
 array(['2 star restaurant', '4 star restaurant', 'Cold drinks',
        'Restaurant with pub', 'Take-away restaurant'], dtype=object),
 array(['Female', 'Male'], dtype=object),
 array(['Individual', 'With Colleagues', 'With Family', 'With Kids'],
       dtype=object),
 array(['Spring', 'Summer', 'Winter'], dtype=object),
 array(['Location A', 'Location B', 'Location C'], dtype=object)]

In [21]:
new_features=[]
for i in range(len(feature_labels)):
    for j in range(len(feature_labels[i])):
        new_features.append(feature_labels[i][j])
print(new_features)

['Divorced', 'Married partner', 'Single', 'Unmarried partner', 'Widowed', '2 star restaurant', '4 star restaurant', 'Cold drinks', 'Restaurant with pub', 'Take-away restaurant', 'Female', 'Male', 'Individual', 'With Colleagues', 'With Family', 'With Kids', 'Spring', 'Summer', 'Winter', 'Location A', 'Location B', 'Location C']

In [22]:
nominal_data=pd.DataFrame(feature_array,columns=new_features)

In [23]:
final_train=pd.concat([train_data,nominal_data],axis=1)
final_train.head()

,offer expiration,income_range,no_visited_Cold drinks,travelled_more_than_15mins_for_offer,Restaur_spend_less_than20,Marital Status,restaurant type,age,Prefer western over chinese,travelled_more_than_25mins_for_offer,...,Individual,With Colleagues,With Family,With Kids,Spring,Summer,Winter,Location A,Location B,Location C
0,48,8,6.0,1,0.0,Married partner,4 star restaurant,36,0,0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,48,7,6.0,0,6.0,Married partner,Take-away restaurant,51,0,0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,48,7,0.0,1,2.0,Single,Cold drinks,26,1,0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
3,10,3,0.0,0,2.0,Single,Take-away restaurant,46,1,0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,48,8,-1.0,1,2.0,Single,4 star restaurant,21,0,1,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0

In [24]:
final_train.drop(columns=['Marital Status','restaurant type','gender','Customer type','Climate','drop location'],inplace=True)

In [25]:
final_train['Offer Accepted'].replace({'Yes':1,'No':0},inplace=True)
final_train.shape

(12379, 45)

In [27]:
# train_data['Maribackend_managerstal Status'] ---- 5 nominal variables
# train_data['restaurant type'].----- 5 nominal values
#train_data['gender'] ------ 2 values
# train_data['Customer type'] ---- 4 values
# train_data['Climate'] ---------- 3 values
# train_data['drop location'] --- 3 values

In [28]:
# Label
final_train['Offer Accepted']

0        0
1        1
2        1
3        0
4        0
        ..
12374    1
12375    1
12376    0
12377    1
12378    1
Name: Offer Accepted, Length: 12379, dtype: int64

In [29]:
# Handling missing values
final1_train = final_train.drop(columns='Offer Accepted')
print(final1_train.shape)
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imp1 = imp.fit(final1_train)
final2_train=imp1.transform(final1_train)
final2_train

(12379, 44)

array([[48.,  8.,  6., ...,  0.,  1.,  0.],
       [48.,  7.,  6., ...,  0.,  1.,  0.],
       [48.,  7.,  0., ...,  1.,  0.,  0.],
       ...,
       [10.,  7.,  6., ...,  0.,  1.,  0.],
       [10.,  1.,  6., ...,  0.,  0.,  1.],
       [48.,  3.,  2., ...,  1.,  0.,  0.]])

In [30]:
final2_train

array([[48.,  8.,  6., ...,  0.,  1.,  0.],
       [48.,  7.,  6., ...,  0.,  1.,  0.],
       [48.,  7.,  0., ...,  1.,  0.,  0.],
       ...,
       [10.,  7.,  6., ...,  0.,  1.,  0.],
       [10.,  1.,  6., ...,  0.,  0.,  1.],
       [48.,  3.,  2., ...,  1.,  0.,  0.]])

In [31]:
x = final2_train
y = final_train['Offer Accepted']
x.shape

(12379, 44)

In [32]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

# Base Model

In [33]:
from sklearn.dummy import DummyClassifier
base_clf = DummyClassifier(strategy='most_frequent')
base_clf.fit(X_train, y_train)
print('Training accuracy:{0:0.2f}'.format(base_clf.score(X_train, y_train)))
print('Testing accuracy:{0:0.2f}'.format(base_clf.score(X_test, y_test)))
print('Score: ', base_clf.score(X_train, y_train))

Training accuracy:0.56
Testing accuracy:0.57
Score:  0.5649803089972736

In [34]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score,classification_report,precision_score,recall_score,f1_score,roc_curve,ConfusionMatrixDisplay

# All models

In [35]:
models = {
     "Logistic Regression":LogisticRegression(),
    "Decision Tree":DecisionTreeClassifier(),
    "Random Forest":RandomForestClassifier(),
    "KNear Neighbor":KNeighborsClassifier(),
    "SVM":SVC(),
    "Bagging":BaggingClassifier(),
    "AdaBoost":AdaBoostClassifier(),
    "Gradient Boost": GradientBoostingClassifier()
    
    
}

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train,y_train)
    
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    
    model_train_f1 = f1_score(y_train,y_train_pred,average='weighted')
   # model_train_accuracy = accuracy_score(y_train,y_train_pred)
   # model_train_precision = precision_score(y_train,y_train_pred,average = 'weighted') 
  # model_train_recall = recall_score(y_train,y_train_pred,average='weighted')
    
    model_test_f1 = f1_score(y_test,y_test_pred,average='weighted')

    # model_test_accuracy = accuracy_score(y_test,y_test_pred)
    # model_test_precision = precision_score(y_test,y_test_pred,average='weighted')
    # model_test_recall = recall_score(y_test,y_test_pred,average='weighted')
    
    print(list(models.keys())[i])
    
    print("Model performance for trianing set")
    
    # print("Accuracy:{:.4f}".format(model_train_accuracy))
    print("F1 score:{:.4f}".format(model_train_f1))
    # print("Precision:{:.4f}".format(model_train_precision))
    # print("Recall:{:.4f}".format(model_train_recall))
    
    print("Model performance for test set")
    
    # print("Accuracy:{:.4f}".format(model_test_accuracy))
    print("F1 score:{:.4f}".format(model_test_f1))
    # print("Precision:{:.4f}".format(model_test_precision))
    # print("Recall:{:.4f}".format(model_test_recall))

/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

Logistic Regression
Model performance for trianing set
F1 score:0.5889
Model performance for test set
F1 score:0.5834
Decision Tree
Model performance for trianing set
F1 score:1.0000
Model performance for test set
F1 score:0.5520
Random Forest
Model performance for trianing set
F1 score:1.0000
Model performance for test set
F1 score:0.6149
KNear Neighbor
Model performance for trianing set
F1 score:0.7092
Model performance for test set
F1 score:0.5509
SVM
Model performance for trianing set
F1 score:0.4079
Model performance for test set
F1 score:0.4080
Bagging
Model performance for trianing set
F1 score:0.9891
Model performance for test set
F1 score:0.5798
AdaBoost
Model performance for trianing set
F1 score:0.6118
Model performance for test set
F1 score:0.5906
Gradient Boost
Model performance for trianing set
F1 score:0.6415
Model performance for test set
F1 score:0.6192

# Logistic Regression

In [36]:

from sklearn.preprocessing import StandardScaler
scale = StandardScaler()

x= scale.fit_transform(final2_train)
y = final_train['Offer Accepted']
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

In [37]:
logistic = LogisticRegression(random_state=42,max_iter=1000)
logistic.fit(X_train,y_train)
y_train_pred = logistic.predict(X_train)
y_test_pred = logistic.predict(X_test)
print(f1_score(y_train,y_train_pred,average='weighted'))
print(f1_score(y_test,y_test_pred))

0.5876545649949277
0.6873417721518987

In [38]:
# from sklearn.linear_model import LogisticRegression
# import numpy as np
# from sklearn.model_selection import GridSearchCV

# model = LogisticRegression()
# param_grid ={'solver': ['lbfgs','liblinear','newton-cg','newton-cholesky','sag','saga'],'penalty':['l2'],'C':np.logspace(-4,4,20)}

# grid_search = GridSearchCV(estimator=model, param_grid=param_grid,cv=10)
# grid_result = grid_search.fit(X_train, y_train)

# print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

In [39]:
logistic1 = LogisticRegression(random_state=42,max_iter=1000,C=0.03359818286283781, penalty='l2',solver='lbfgs')
logistic1.fit(X_train,y_train)
y_train_pred = logistic1.predict(X_train)
y_test_pred = logistic1.predict(X_test)
print(f1_score(y_train,y_train_pred,average='weighted'))
print(f1_score(y_test,y_test_pred))

0.587472709945453
0.6868686868686869

# Adaboost classifier

In [40]:
#parameters = {"n_estimators":[20,30,40,50],"learning_rate":[0.01,0.1,0.5,1,1.5,2,2.5]}

In [41]:
#from sklearn.model_selection import GridSearchCV
#cv = GridSearchCV(adaboost,parameters,cv=10)
#cv.fit(X_train,y_train.values.ravel())

In [42]:
#cv.best_params_

In [43]:
adaboost = AdaBoostClassifier(random_state=42,learning_rate=1.5,n_estimators=50)
adaboost.fit(X_train,y_train)
pred = adaboost.predict(X_test)
print("Test Score:",adaboost.score(X_test,y_test))
print("Train score:",adaboost.score(X_train,y_train))

Test Score: 0.6046042003231018
Train score: 0.6233464606684843

# Bagging Classifier

In [44]:
from sklearn.ensemble import BaggingClassifier
bagging = BaggingClassifier()
bagging.fit(X_train,y_train)

BaggingClassifier()

In [45]:
pred = bagging.predict(X_test)
print("Test Score:",bagging.score(X_test,y_test))
print("Train score:",bagging.score(X_train,y_train))

Test Score: 0.5702746365105008
Train score: 0.9878824598606483

In [46]:
parameters = {'n_estimators':[10,50,100,200,1000],
             'max_samples':[1,2,3,4,5,6],
             'bootstrap':['true','false'],
             'bootstrap_features':['true','false']}

In [47]:
#from sklearn.model_selection import GridSearchCV
#cv = GridSearchCV(bagging,parameters,cv=10)
#cv.fit(X_train,y_train.values.ravel())

In [48]:
#cv.best_params_

In [49]:
bc = BaggingClassifier(max_samples=6,n_estimators=1000,bootstrap=False,random_state=42,)
bc.fit(X_train,y_train)

BaggingClassifier(bootstrap=False, max_samples=6, n_estimators=1000,
                  random_state=42)

In [50]:
pred = bc.predict(X_test)
print("Test Score:",bc.score(X_test,y_test))
print("Train score:",bc.score(X_train,y_train))

Test Score: 0.5702746365105008
Train score: 0.569322427547208

# Gradient Boosting Classifier

In [51]:
from sklearn.ensemble import GradientBoostingClassifier

In [52]:
cf =GradientBoostingClassifier()

In [53]:
parameters = {
    "n_estimators":[80,90,95,100,110,120],
    "max_depth":[1,3,4,5,6,7,9],
    "learning_rate":[0.1]
}

In [54]:
#from sklearn.model_selection import GridSearchCV
#cv = GridSearchCV(cf,parameters,cv=10)
#cv.fit(X_train,y_train.values.ravel())

In [55]:
#cv.best_params_

In [56]:

cf =GradientBoostingClassifier(learning_rate=0.1,max_depth=5,n_estimators=90,random_state=42)
cf.fit(X_train,y_train)

GradientBoostingClassifier(max_depth=5, n_estimators=90, random_state=42)

In [57]:
pred = cf.predict(X_test)
print("Test Score:",cf.score(X_test,y_test))
print("Train score:",cf.score(X_train,y_train))
print(classification_report(y_test,pred))

Test Score: 0.6316639741518578
Train score: 0.742098354034131
              precision    recall  f1-score   support

           0       0.61      0.44      0.51      1077
           1       0.64      0.78      0.71      1399

    accuracy                           0.63      2476
   macro avg       0.62      0.61      0.61      2476
weighted avg       0.63      0.63      0.62      2476

In [58]:
test_data=pd.read_csv('/kaggle/input/marketing-strategy-personalised-offer/test_data.csv')
test_data.isnull().sum()

offer expiration                           0
income_range                               0
no_visited_Cold drinks                    90
travelled_more_than_15mins_for_offer       0
Restaur_spend_less_than20                 61
Marital Status                             0
restaurant type                            0
age                                        0
Prefer western over chinese                0
travelled_more_than_25mins_for_offer       0
travelled_more_than_5mins_for_offer        0
no_visited_bars                           50
gender                                     0
car                                     5262
restuarant_same_direction_house            0
Cooks regularly                            0
Customer type                              0
Qualification                              0
is foodie                                  0
no_Take-aways                             60
Job/Job Industry                           0
restuarant_opposite_direction_house        0
has Children                               0
visit restaurant with rating (avg)         0
temperature                                0
Restaur_spend_greater_than20             104
Travel Time                                0
Climate                                    0
drop location                              0
Prefer home food                           0
dtype: int64

In [59]:
test_data['no_visited_Cold drinks'].replace({'never':-1,'less1':0,'1~3':2,'4~8':6,'gt8':9},inplace=True)
test_data['Restaur_spend_less_than20'].replace({'never':-1,'less1':0,'1~3':2,'4~8':6,'gt8':9},inplace=True)
test_data['no_visited_bars'].replace({'never':-1,'less1':0,'1~3':2,'4~8':6,'gt8':9},inplace=True)
test_data['no_Take-aways'].replace({'never':-1,'less1':0,'1~3':2,'4~8':6,'gt8':9},inplace=True)
test_data['Restaur_spend_greater_than20'].replace({'never':-1,'less1':0,'1~3':2,'4~8':6,'gt8':9},inplace=True)

In [60]:
test_data.drop(columns=['Job/Job Industry','car'],inplace=True)
print(test_data.columns)
print(test_data.shape)

Index(['offer expiration', 'income_range', 'no_visited_Cold drinks',
       'travelled_more_than_15mins_for_offer', 'Restaur_spend_less_than20',
       'Marital Status', 'restaurant type', 'age',
       'Prefer western over chinese', 'travelled_more_than_25mins_for_offer',
       'travelled_more_than_5mins_for_offer', 'no_visited_bars', 'gender',
       'restuarant_same_direction_house', 'Cooks regularly', 'Customer type',
       'Qualification', 'is foodie', 'no_Take-aways',
       'restuarant_opposite_direction_house', 'has Children',
       'visit restaurant with rating (avg)', 'temperature',
       'Restaur_spend_greater_than20', 'Travel Time', 'Climate',
       'drop location', 'Prefer home food'],
      dtype='object')
(5305, 28)

In [61]:
test_data['offer expiration'].replace({'2days':48,'10hours':10},inplace=True)
test_data['income_range'].replace({'Less than ₹12500':0,'₹12500 - ₹24999':1,'₹25000 - ₹37499':2,
                                       '₹37500 - ₹49999':3,'₹50000 - ₹62499':4,'₹62500 - ₹74999':5,
                                       '₹75000 - ₹87499':6,'₹87500 - ₹99999':7,'₹100000 or More':8},inplace=True)

test_data['age'].replace({'below21':20,'21':21,'26':26,'31':31,'36':36,'41':41,'46':46,
                          '50plus':51},inplace=True)
test_data['Qualification'].replace({'Some High School':0,'High School Graduate':1,'Some college - no degree':2,
        'Bachelors degree':3,'Associates degree':4,'Graduate degree (Masters or Doctorate)':5},inplace=True)

In [62]:
ohe.fit_transform(test_data[['Marital Status','restaurant type','gender','Customer type','Climate','drop location']]).toarray()
feature_test_array =ohe.fit_transform(test_data[['Marital Status','restaurant type','gender','Customer type','Climate','drop location']]).toarray()
feature_test_labels =ohe.categories_

In [63]:
new_test_features=[]
for i in range(len(feature_test_labels)):
    for j in range(len(feature_test_labels[i])):
        new_test_features.append(feature_test_labels[i][j])
print(new_test_features)

['Divorced', 'Married partner', 'Single', 'Unmarried partner', 'Widowed', '2 star restaurant', '4 star restaurant', 'Cold drinks', 'Restaurant with pub', 'Take-away restaurant', 'Female', 'Male', 'Individual', 'With Colleagues', 'With Family', 'With Kids', 'Spring', 'Summer', 'Winter', 'Location A', 'Location B', 'Location C']

In [64]:
nominal_test_data=pd.DataFrame(feature_test_array,columns=new_test_features)

In [65]:
final_test=pd.concat([test_data,nominal_test_data],axis=1)
final_test.head()

,offer expiration,income_range,no_visited_Cold drinks,travelled_more_than_15mins_for_offer,Restaur_spend_less_than20,Marital Status,restaurant type,age,Prefer western over chinese,travelled_more_than_25mins_for_offer,...,Individual,With Colleagues,With Family,With Kids,Spring,Summer,Winter,Location A,Location B,Location C
0,48,3,2.0,1,2.0,Divorced,Take-away restaurant,51,0,1,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,10,2,6.0,0,2.0,Unmarried partner,Cold drinks,21,1,0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
2,48,8,-1.0,1,-1.0,Single,Cold drinks,21,1,0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,48,2,-1.0,1,2.0,Married partner,Restaurant with pub,41,0,0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
4,10,1,-1.0,0,2.0,Single,2 star restaurant,31,1,0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

In [66]:
final_test.drop(columns=['Marital Status','restaurant type','gender','Customer type','Climate','drop location'],inplace=True)
final_test.shape

(5305, 44)

In [67]:
final_test.isnull().sum()

offer expiration                          0
income_range                              0
no_visited_Cold drinks                   90
travelled_more_than_15mins_for_offer      0
Restaur_spend_less_than20                61
age                                       0
Prefer western over chinese               0
travelled_more_than_25mins_for_offer      0
travelled_more_than_5mins_for_offer       0
no_visited_bars                          50
restuarant_same_direction_house           0
Cooks regularly                           0
Qualification                             0
is foodie                                 0
no_Take-aways                            60
restuarant_opposite_direction_house       0
has Children                              0
visit restaurant with rating (avg)        0
temperature                               0
Restaur_spend_greater_than20            104
Travel Time                               0
Prefer home food                          0
Divorced                                  0
Married partner                           0
Single                                    0
Unmarried partner                         0
Widowed                                   0
2 star restaurant                         0
4 star restaurant                         0
Cold drinks                               0
Restaurant with pub                       0
Take-away restaurant                      0
Female                                    0
Male                                      0
Individual                                0
With Colleagues                           0
With Family                               0
With Kids                                 0
Spring                                    0
Summer                                    0
Winter                                    0
Location A                                0
Location B                                0
Location C                                0
dtype: int64

In [68]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imp1 = imp.fit(final1_train)
final2_test=imp1.transform(final_test)
final2_test.shape

(5305, 44)

In [69]:
x_test = final2_test
y = final_train['Offer Accepted']

In [70]:
prediction =cf.predict(x_test)

prediction

array([0, 1, 0, ..., 0, 1, 1])

In [71]:
submission=pd.DataFrame(columns=['id','Offer Accepted'])
submission['id']=[i for i in range(len(prediction))]
submission['Offer Accepted']=prediction
submission['Offer Accepted'].replace({0:'No',1:'Yes'},inplace=True)

In [72]:
submission.to_csv('submission.csv',index=False)

In [73]:
submission

        id Offer Accepted
0        0             No
1        1            Yes
2        2             No
3        3             No
4        4             No
...    ...            ...
5300  5300             No
5301  5301             No
5302  5302             No
5303  5303            Yes
5304  5304            Yes

[5305 rows x 2 columns]